.\" Man page for no.
.\" Contact tabledmetamethods@gmail.com to correct errors or typos.

.TH man 1 "Jan 1, 2024" "GNU ballutils 1.0" "General Commands Manual"

.SH NAME
no \- output a string repeatedly until killed

.SH SYNOPSIS
no [STRING]

no OPTION

.SH DESCRIPTION
Repeatedly output a line with all specified STRING(s), or 'n'.

.SH OPTIONS
.TP
.B \-\-help
display this help and exit
.TP
.B \-\-version
output version information and exit

.SH AUTHOR
Written by metamethods.

.SH REPORTING BUGS
GNU ballutils online help: <https://github.com/metamethods/no>

Report any translation bugs to <https://github.com/metamethods/metamethods/issues> (But why would you do that)

.SH COPYRIGHT
Copyright  ©  2024  Free Software Foundation, Inc.  License GPLv3+: GNU

GPL version 3 or later <https://gnu.org/licenses/gpl.html>.

This is free software: you are free  to  change  and  redistribute  it.

There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
Full documentation at: <https://github.com/metamethods/no>

or available locally via: info '(ballutils) no invocation'