name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo test --all-features

    build:
        runs-on: ${{ matrix.target }}
        needs: test

        strategy:
            matrix:
                target: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo build --release
            - uses: actions/upload-artifact@v4
              with:
                  name: "no-${{ matrix.target }}"
                  path: |
                    target/release/no
                    target/release/no.exe